import * as React from 'react';
import { RouteComponentProps } from 'react-router';
import * as YamlP from 'yaml';

import { Flex, FlexItem, PageSection, Title } from '@patternfly/react-core';

import { ApplicationSetKind } from '../../models/ApplicationSetModel';
import { useGitOpsTranslation } from '../../utils/hooks/useGitOpsTranslation';

import './AppSetDetailsTab.scss';
// import { SidebarSectionHeading } from '@gitops/topology/sidebar/DeploymentSideBarDetails';

type AppSetMatchExpressionsTabProps = RouteComponentProps<{ ns: string; name: string }> & {
  obj?: ApplicationSetKind;
  customData?: object;
};

const AppSetMatchExpressionsTab: React.FC<AppSetMatchExpressionsTabProps> = ({ obj, customData }) => {
  const { t } = useGitOpsTranslation();

  const yaml = obj?.spec?.strategy?.rollingSync?.steps[parseInt(customData?.step) - 1]?.matchExpressions || {};

  return (
    <>
      <PageSection>
        <Title headingLevel="h2" className="co-section-heading">
          {t('Progressive Sync Step ' + customData?.step)}
        </Title>
        <Flex
          justifyContent={{ default: 'justifyContentSpaceEvenly' }}
          direction={{ default: 'column', lg: 'row' }}
        >
          <Flex flex={{ default: 'flex_2' }}>
            <FlexItem fullWidth={{ default: 'fullWidth' }}>
            <div className="ocs-sidebar-tabsection">
              {/* <div className="co-m-pane__heading-owner">
                <SidebarSectionHeading text={'Progressive Sync Step ' + customData?.step} />
              </div> */}
            </div>
            <div className="overview__sidebar-pane-body resource-overview__body">
              <div className="resource-overview__summary">
                {'Match Expressions:'}
                <pre>{YamlP.stringify(yaml, null, 2)}</pre>

                {/* <DescriptionList>
                  <DetailsItem label={t('plugin__gitops-public~Step')} obj={applicationSet} path={'spec.strategy.rollingSync.steps[' + selectedNode?.getData().step + '].matchExpressions[0].key'} />
                </DescriptionList> */}
              </div>
            </div>

              {/* <BaseDetailsSummary obj={obj} model={ApplicationSetModel} /> */}
            </FlexItem>
          </Flex>
          {/* <Flex flex={{ default: 'flex_2' }} direction={{ default: 'column' }}>
            <FlexItem>
              <DescriptionList className="pf-c-description-list">
                <DetailsDescriptionGroup
                  title={t('Status')}
                  help={t('Current health status of the ApplicationSet.')}
                >
                  <HealthStatus status={appSetStatus} />
                </DetailsDescriptionGroup>

                <DetailsDescriptionGroup
                  title={t('Generated Apps')}
                  help={t('Number of applications generated by this ApplicationSet.')}
                >
                </DetailsDescriptionGroup>

                <DetailsDescriptionGroup
                  title={t('Generators')}
                  help={t('Number of generators configured in this ApplicationSet.')}
                >
                </DetailsDescriptionGroup>

                <DetailsDescriptionGroup
                  title={t('App Project')}
                  help={t('Argo CD project that this ApplicationSet belongs to.')}
                >
                  <ResourceLink
                    namespace={obj?.metadata?.namespace}
                    groupVersionKind={{
                      group: 'argoproj.io',
                      version: 'v1alpha1',
                      kind: 'AppProject',
                    }}
                    name={spec.template?.spec?.project || 'default'}
                  />
                </DetailsDescriptionGroup>

                {spec.template?.spec?.source?.repoURL && (
                  <DetailsDescriptionGroup
                    title={t('Repository')}
                    help={t('Git repository URL where the ApplicationSet configuration is stored.')}
                  >
                    <a
                      href={spec.template.spec.source.repoURL}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {spec.template.spec.source.repoURL}
                    </a>
                  </DetailsDescriptionGroup>
                )}
              </DescriptionList> */}
            {/* </FlexItem> */}
          {/* </Flex> */}
        </Flex>
      </PageSection>

      <PageSection>
        <Title headingLevel="h2" className="co-section-heading">
        </Title>
      </PageSection>
    </>
  );
};

export default AppSetMatchExpressionsTab;
